title: "TEZDOCS 테마!!"
top-mgs: "허접한 깃허브 페이지용 기술블로그 테마"
bottom-msg: "Themed by Tez &&<br/>Powered by Github Pages"
url: "https://github.com/teznote/tezdocs"
permalink: /post/:title
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
future: true
main-color: "#ddeeff"
cats:
- id: study
  title: My Programming Study
  subs:
  - id: python
    title: Python
    order: title
  - id: javascript
    title: Javascript
  - id: cpp
    title: C++
    order: updated
- id: todo
  title: My To-do Lists
  subs:
  - id: home
    title: at Home
    order: updated-desc
  - id: work
    title: at Work
    order: title-desc