title: "TEZDOCS 테마"
desc: "깃허브 페이지에서 허접하게나마 기술블로그를 만들기 위한 테마입니다."
url: "https://github.com/teznote/tezdocs"
permalink: /post/:title
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
future: true
tags:
- id: study
  title: My Programming Study
  subs:
  - id: python
    title: Python
  - id: javascript
    title: Javascript
  - id: cpp
    title: C++
- id: todo
  title: My To-do Lists
  subs:
  - id: home
    title: at Home
  - id: work
    title: at Work