title: Tez'Docs
description: Simple blog theme for Github Pages
footer: This blog is powered by Github Pages,<br />and themed by Jekyll.
permalink: /post/:title
baseurl: /tezdocs

kramdown:
  syntax_highlighter_opts:
    disable: true

navtags:
- id: todo
  title: To-Dos
- id: diary
  title: My Diary
- id: coding
  title: Coding